name: Build
on:
  # Only run workflow when there is push to main or when there is a pull request to main
  workflow_dispatch:
jobs:
  test:
    # When running with act (https://github.com/nektos/act), these lines need to be appended with the ACT variable
    # to force each job to run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
    - name: Pre-commit checks
      run: pre-commit run --all-files
    - name: Test with pytest
      # Create the ssh key file once for all testing
      run: |
        ssh-keygen -t ecdsa -m PEM -N '' -f /tmp/buildrunner-test-id_rsa
        pytest -v -m "not serial" --numprocesses=auto --junitxml=test-reports/non-serial-test-results.xml
        pytest -v -m "serial" --junitxml=test-reports/serial-test-results.xml
        python scripts/combine_xml.py test-reports/serial-test-results.xml test-reports/non-serial-test-results.xml > test-reports/test-result.xml
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: always()
      with:
        files: test-reports/test-results.xml
        check_name: "Test Results ${{ matrix.python-version }}"
        github_retries: 10
        secondary_rate_limit_wait_seconds: 60.0
